# Worksheet 04

Name: Pranesh Jayasundar
UID: U08334002

### Topics

- Distance & Similarity
- Cost Functions
- K means

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

- p: is just a parameter, and p >= 1. When p = 2 it's Euclidean distance, and when p = 1 it's Manhattan distance. "p" is a positive integer that determines the power to which the distances between the elements are raised.
- d: The parameter "d" represents the number of dimensions in the space.

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

- The Euclidean distance is the most commonly used distance metric and is the straight line distance between two points in a space. It is calculated as the square root of the sum of the squares of the differences between the coordinates of the two points

- On the other hand, the Manhattan distance, when p = 1 in the minkowski distance, measures the sum of the absolute differences between the coordinates of the two points. It only takes into account the change in each dimension individually and is not sensitive to changes in other dimensions

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

- I think, it might tend to become closer to 1, when "p" increases. Say when p = 100, it would be 1.001, and when p = 10000, the distance might be 1.00000001
- We can basically come up with the intuition; any power of 1 ~ 1.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

- No, it's not the distance function when p < 1 because it violates the distance function properties. Let's take three points A, B, C - (0, 0), (0, 1), (1, 0). The hypotenuse is greater than the sum of other two sides which violates the triangle inequality.

e) when would you use cosine similarity over the euclidan distance?

- Cosine similarity is used for text and document analysis, while Euclidean distance is used for finding the distance between points in a space.

f) what does the jaccard distance account for that the manhattan distance doesn't?

- Jaccard distance takes into consideration the similar words or similarity, whereas the manhattan distance doesn't take the similarity. 
- Jaccard distance is calculated based on the similar words between 2 documents, and manhattan distance is the absolute difference between 2 sets.

#### Part 2

Consider the following two sentences:

In [3]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [4]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [5]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['my', 'name', 'hello', 'is', 'Bob', 'Alice']
[1, 1, 1, 1, 0, 1]


Let's add a new sentence to our corpus:

In [6]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [7]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['my', 'name', 'hello', 'hi', 'is', 'Bob', 'Alice', 'Claude']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [8]:
v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
print(v1)
print(v2)
print(v3)

[1, 1, 1, 0, 1, 0, 1, 0]
[1, 1, 1, 0, 1, 1, 0, 0]
[1, 1, 0, 1, 1, 0, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [15]:
def manhattan_distane(x, y):
    # To check x and y are of the same dimension
    res = 0
    for i in range (len(x)):
        res += abs(x[i] - y[i])

    return res

print('Distance between v1 and v2:', manhattan_distane(v1, v2))
print('Distance between v2 and v3:', manhattan_distane(v2, v3))
print('Distance between v1 and v3:', manhattan_distane(v1, v3))

Distance between v1 and v2: 2
Distance between v2 and v3: 4
Distance between v1 and v3: 4


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [18]:
# Matrix for all the above mentioned vectors
# {hi, Alice, hello, claude, Bob, my, name, is}

import numpy as np

s4 = "hi Alice"
corpus.append(s4)

s5 = "hello Claude"
corpus.append(s5)

s6 = "Bob my name is Claude"
corpus.append(s6)

s7 = "hi Claude my name is Alice"
corpus.append(s7)

s8 = "hello Bob"
corpus.append(s8)


v4 = [1 if x in s4 else 0 for x in all_words]

v5 = [1 if x in s5 else 0 for x in all_words]

v6 = [1 if x in s6 else 0 for x in all_words]

v7 = [1 if x in s7 else 0 for x in all_words]

v8 = [1 if x in s8 else 0 for x in all_words]

matrix = []
matrix.append(v4)
matrix.append(v5)
matrix.append(v6)
matrix.append(v7)
matrix.append(v8)

matrix = np.array(matrix)
print(matrix)

[[0 0 0 1 0 0 1 0]
 [0 0 1 0 0 0 0 1]
 [1 1 0 0 1 1 0 1]
 [1 1 0 1 1 0 1 1]
 [0 0 1 0 0 1 0 0]]


e) How many rows and columns does this matrix have?

The dimension of the matrix is 5 x 8

Rows: 5
Columns: 8

f) When using the Manhattan distance, which two sentences are the most similar?

In [29]:
lowest_distance = manhattan_distane(v4, v5)
most_similar = (1, 2) # By default

for i in range(1, 6):
    for j in range(i + 1, 6):
        if manhattan_distane(matrix[i - 1], matrix[j - 1]) < lowest_distance:
            lowest_distance = manhattan_distane(matrix[i - 1], matrix[j - 1])
            most_similar = (i, j)

            print('The most similar sentences are sentence', str(most_similar[0]), 'and sentence', str(most_similar[1]))

The most similar sentences are sentence 2 and sentence 5


### Cost Function

Solving Data Science problems often starts by defining a metric with which to evaluate solutions were you able to find some. This metric is called a cost function. Data Science then backtracks and tries to find a process / algorithm to find solutions that can optimize for that cost function.

For example suppose you are asked to cluster three points A, B, C into two non-empty clusters. If someone gave you the solution `{A, B}, {C}`, how would you evaluate that this is a good solution?

Notice that because the clusters need to be non-empty and all points must be assigned to a cluster, it must be that two of the three points will be together in one cluster and the third will be alone in the other cluster.

In the above solution, if A and B are closer than A and C, and B and C, then this is a good solution. The smaller the distance between the two points in the same cluster (here A and B), the better the solution. So we can define our cost function to be that distance (between A and B here)!

The algorithm / process would involve clustering together the two closest points and put the third in its own cluster. This process optimizes for that cost function because no other pair of points could have a lower distance (although it could equal it).

### K means

a) (1-dimensional clustering) Walk through Lloyd's algorithm step by step on the following dataset:

`[0, .5, 1.5, 2, 6, 6.5, 7]` (note: each of these are 1-dimensional data points)

Given the initial centroids:

`[0, 2]`

Iteration 1:

(1) Step 1: Randomly pick k centers
- Here the k value is 2, and the centers are [0, 2].

(2) Step 2: Assign each point in the dataset to its closest center.
- 0: assigned to center 0
- 0.5: assigned to center 0
- 1.5: assigned to center 2
- 2: assigned to center 2
- 6: assigned to center 2
- 6.5: assigned to center 2
- 7: assigned to center 2

(3) Step 3: Compute the new centers as the means of each cluster
- New mean: (0 + 0.5)/2 = 0.25
- New mean: (1.5 + 2 + 6 + 6.5 + 7)/5 = 4.6

New centroid: [0.25, 4.6]

(4) Step 4: Repeat step 2 and 3 until convergence



Iteration 2:

(1) Step 1: Randomly pick k centers
- Here the k value is 2, and the centers are [0.25, 4.6].

(2) Step 2: Assign each point in the dataset to its closest center.
- 0: assigned to center 0.25
- 0.5: assigned to center 0.25
- 1.5: assigned to center 0.25
- 2: assigned to center 0.25
- 6: assigned to center 4.6
- 6.5: assigned to center 4.6
- 7: assigned to center 4.6

(3) Step 3: Compute the new centers as the means of each cluster
- New mean: (0 + 0.5 + 1.5 + 2)/4 = 1
- New mean: (6 + 6.5 + 7)/3 = 6.5

New centroid: [1, 6.5]

(4) Step 4: Repeat step 2 and 3 until convergence



Iteration 3:

(1) Step 1: Randomly pick k centers
- Here the k value is 2, and the centers are [1, 6.5].

(2) Step 2: Assign each point in the dataset to its closest center.
- 0: assigned to center 1
- 0.5: assigned to center 1
- 1.5: assigned to center 1
- 2: assigned to center 1
- 6: assigned to center 6.5
- 6.5: assigned to center 6.5
- 7: assigned to center 6.5

(3) Step 3: Compute the new centers as the means of each cluster
- New mean: (0 + 0.5 + 1.5 + 2)/4 = 1
- New mean: (6 + 6.5 + 7)/3 = 6.5

New centroid: [1, 6.5]

(4) Final, no more changes in the centroid.

b) Describe in plain english what the cost function for k means is.

- The cost function for K-Means is a measure of how close each data point is to the center of its assigned cluster. 
- The algorithm tries to minimize this measure so that the clusters are tight and well defined.

c) For the same number of clusters K, why could there be very different solutions to the K means algorithm on a given dataset?

- Initial centroid selection plays a huge role, (i.e) the 'k' random centers
- Outliers can have a significant impact on the solution of K-Means. If there are outliers in the dataset, the algorithm may converge to a solution that is heavily influenced by them, rather than the actual cluster centers.

d) Does Lloyd's Algorithm always converge? Why / why not?

- Does not always converge to a global optimum solution. 
- It can sometimes converge to a local minimum, which may not be the best solution for the given dataset.
- The optimization process used by the K-Means algorithm can get stuck in a local minimum, where the cost function no longer decreases.
- To overcome this problem, we can initialize random centroids multiple time, and run Lloyd's algorithm to improve the chances of finding a better solution.